variable_texto = "Hola Mundo"
#print (variable_texto.upper())
#print (variable_texto.lower())
#print (variable_texto.find("a"))
#print (variable_texto.upper().find(str.upper("OL")))
nueva_variable_texto_reemplazo = variable_texto.replace("Mundo", "Estudiantes Beyond")
#print (variable_texto.replace("Mundo","Estudiantes Beyond"))
#print (variable_texto)
print ("Mundo" in nueva_variable_texto_reemplazo)
print ("Mundo" in variable_texto)
